### ISSUE TITLE
Build crashes if assets/ directory is missing

### ISSUE THREAD

**Issue by serhiipalash** [blogfoster/blogfoster-scripts#1]
<img width="1280" alt="screen shot 2018-01-20 at 15 43 27" src="https://user-images.githubusercontent.com/14208343/35184047-ff7f9eca-fdf8-11e7-831a-d6e5279c1f18.png">

**Comment by cangoektas** [comment]
Hey, thanks a lot for reporting! Just fixed this and will publish `0.0.2` in a couple of minutes :)

**Comment by cangoektas** [comment]
...and it's up! 👍

**Comment by serhiipalash** [comment]
Thanks!
